version: "3"

services:
  
  film-db:
    image: 'postgres:latest'
    container_name: film-db
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=film
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d film"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  author-db:
    image: 'postgres:latest'
    container_name: author-db
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=author
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d author"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  film-service:
    build:
      context: film-service
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5433/film
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/film/__health/" ]
      interval: 10s
      timeout: 5s
      retries: 5

    depends_on:
      film-db:
        condition: service_healthy
    links:
      - film-db

  author-service:
    build:
      context: author-service
      dockerfile: Dockerfile
    ports:
    - 8082:8082
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5434/author
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/author/__health/" ]
      interval: 10s
      timeout: 5s
      retries: 5

    depends_on:
      author-db:
        condition: service_healthy
      film-service:
        condition: service_started
    links:
      - author-db
      - film-service

  krakend_ce:
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
    image: devopsfaith/krakend:2.1.3
    ports:
      - "1234:1234"
      - "8080:8080"
      - "8090:8090"
      - "8091:8091"
    depends_on:
      film-service:
        condition: service_started
      author-service:
        condition: service_started
    links:
      - film-service
      - author-service

  jaeger-allinone:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 16686:16686
      - 14268:14268
    depends_on:
      krakend_ce:
        condition: service_started
    links:
      - krakend_ce
  influxdb:
    image: influxdb:1.8.10
    environment:
      - "INFLUXDB_DB=krakend"
      - "INFLUXDB_USER=kraken"
      - "INFLUXDB_USER_PASSWORD=pass"
      - "INFLUXDB_ADMIN_USER=admin"
      - "INFLUXDB_ADMIN_PASSWORD=admin"
    ports:
      - "8086:8086"
  grafana:
    build: './config/grafana'
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus

  keycloak-db:
    image: 'postgres:latest'
    container_name: keycloak-db
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=keycloak
    networks:
      - local-keycloak

  keycloak:
    depends_on:
      - keycloak-db
    container_name: local_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin1
      KEYCLOAK_PASSWORD: admin1
    image: jboss/keycloak
    ports:
      - "8484:8080"
    networks:
      - local-keycloak

networks:
  monitoring:
  local-keycloak:
