apiVersion: 1

datasources:
  - name: Prometheus
    label: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
  - access: 'proxy'
    editable: true
    is_default: true
    name: 'influx'
    org_id: 1
    type: 'influxdb'
    url: 'http://host.docker.internal:8086'
    version: 1
    user: kraken
    password: pass
    database: krakend
